---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: NetApp SnapMirror透過 LAN 或 WAN 高速複製數據，因此您可以在虛擬和傳統環境中獲得高數據可用性和快速數據複製。當您將資料複製到NetApp儲存系統並不斷更新輔助資料時，您的資料將保持最新狀態並在您需要時保持可用。不需要外部複製伺服器。 
---
= 了解NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror透過 LAN 或 WAN 高速複製數據，因此您可以在虛擬和傳統環境中獲得高數據可用性和快速數據複製。當您使用NetApp Replication將資料複製到NetApp儲存系統並不斷更新二級資料時，您的資料將保持最新狀態並在您需要時保持可用。不需要外部複製伺服器。



[[netapp-console]]
== NetApp Console

可以透過NetApp Console存取NetApp Replication 。

控制台在企業級層級提供跨內部部署與雲端環境的 NetApp 儲存設備與資料服務的集中式管理。存取與使用 NetApp 資料服務需要控制台。作為管理介面，它使您能夠從一個介面管理許多儲存資源。控制台管理員可以控制企業內所有系統對儲存設備與服務的存取。

您無需許可證或訂閱即可開始使用控制台。只有當您需要在雲端部署控制台代理程式以確保與儲存系統或 NetApp 資料服務的連線時，才會產生費用。但是，某些可透過控制台存取的 NetApp 資料服務需要獲得許可或訂閱才能使用。

深入瞭解 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"]。



[[features]]
== 特徵

* 在ONTAP儲存系統之間複製數據，以支援到雲端或雲端之間的備份和災難復原。
* 透過高可用性確保您的 DR 環境的可靠性。
* ONTAP 儲存系統之間的高效區塊層級複寫快速且有效率，並具有精細的恢復點，可用於災難恢復和備份。




[[cost]]
== 成本

NetApp不會向您收取使用NetApp Replication 的費用，但您需要向您的雲端供應商查詢適用的資料入口和出口費用。



[[supported-systems]]
== 支援的系統

NetApp Replication支援以下類型的系統之間的資料複製。

[cols="30,30"]
|===
| 來源系統 | 支援的目標系統 


| Cloud Volumes ONTAP  a| 
* 適用於ONTAP 的Amazon FSx
* Cloud Volumes ONTAP
* 內部部署 ONTAP 叢集




| 內部部署 ONTAP 叢集  a| 
* 適用於ONTAP 的Amazon FSx
* Cloud Volumes ONTAP
* 內部部署 ONTAP 叢集




| 適用於ONTAP 的Amazon FSx  a| 
* 適用於ONTAP 的Amazon FSx
* Cloud Volumes ONTAP
* 內部部署 ONTAP 叢集


|===


[[how-data-replication-works]]
== 資料複製的工作原理

NetApp Replication 簡化了使用 SnapMirror 和 SnapVault 技術在分隔的 ONTAP 系統上的 Volume 之間的資料複寫。若要設定複寫，您只需識別來源 Volume 和目的地 Volume，然後選擇複寫原則和排程。

對於Cloud Volumes ONTAP， NetApp Replication會購買所需的磁碟、設定關係、套用複製策略，然後啟動磁碟區之間的基準傳輸。


NOTE: 基線傳輸包括來源資料的完整副本。後續傳輸包含來源資料的差異副本。



[[supported-data-protection-configurations]]
== 支援的資料保護配置

NetApp Replication支援簡單、扇出和級聯資料保護配置：

* 在簡單的配置中，複製從磁碟區 A 發生到磁碟區 B。
* 在扇出配置中，複製從磁碟區 A 發生到多個目標。
* 在級聯配置中，複製從磁碟區 A 發生到磁碟區 B，再從磁碟區 B 發生到磁碟區 C。




[[replicate-data-using-netapp-backup-and-recovery]]
== 使用NetApp Backup and Recovery複製數據

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^] 可讓您在分隔的 ONTAP 系統上的 Volume 之間複寫資料，同時將相同的資料備份到物件儲存。如果您想要在單一服務中管理相同 ONTAP 資料的複寫與備份到物件保護，請考慮使用 NetApp Backup and Recovery。

NetApp Replication 支援下列 Backup and Recovery 中未提供的功能。

* Backup and Recovery 目前不支援將資料複寫到 FSx for ONTAP 系統或從 FSx for ONTAP 系統複寫資料。
* Backup and Recovery 不支援建立 Volume 的一次性複寫。


此外，級聯關係在複寫中更容易設定。如果您需要這些功能，請使用 NetApp Replication。
